### ISSUE TITLE
vocab and char file cannot be found

### ISSUE THREAD

**Issue by Sjzwind** [JasonForJoy/DIM#1]
Thanks for you open code. I couldn't find the vocab file, char vocab file and embedded vector file, Could you release these files? Looking forward to your reply.

**Comment by JasonForJoy** [comment]
@Sjzwind Sorry for the late reply. We have shared these files on the google drive link below and checked again that the link is accessible. You may need a VPN to download the files because Chinese Great Wall blocks it. If you still cannot download the files, feel free to email me (gujc@mail.ustc.edu.cn), and I will send you the files.
https://drive.google.com/open?id=1gGZfQ-m7EGo5Z1Ts93Ta8GPJpdIQqckC
